### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by FanMclaine**
image

his idea was to read discordjs tutorials

### CODE REVIEW

**Comment by Carnagion** [comment]
Too many commits to merge at once, especially when some of them are unfinished
Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?

**Comment by FanMclaine** [comment]
> Too many commits to merge at once, especially when some of them are unfinished Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?

Is help.js not working or useless?

**Comment by Carnagion** [comment]
> 
> 
> > Too many commits to merge at once, especially when some of them are unfinished Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?
> 
> Is help.js not working or useless?

Should work I believe
Only things that really need to be there are the README, timecheck.js, and help.js
Everything else can go

**Comment by FanMclaine** [comment]
> > > Too many commits to merge at once, especially when some of them are unfinished Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?
> > 
> > 
> > Is help.js not working or useless?
> 
> Should work I believe Only things that really need to be there are the README, timecheck.js, and help.js Everything else can go

coolio, so what's the problem?

**Comment by Carnagion** [comment]
> 
> 
> > > > Too many commits to merge at once, especially when some of them are unfinished Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?
> > > 
> > > 
> > > Is help.js not working or useless?
> > 
> > 
> > Should work I believe Only things that really need to be there are the README, timecheck.js, and help.js Everything else can go
> 
> coolio, so what's the problem?

random/Screenshot_69420.png lmao
It doesn't need to be there

**Comment by FanMclaine** [comment]
> > > > > Too many commits to merge at once, especially when some of them are unfinished Perhaps it'd be better to create a different PR with just the timecheck command, then I can accept that and update it with the working version, then create a separate branch for the rest?
> > > > 
> > > > 
> > > > Is help.js not working or useless?
> > > 
> > > 
> > > Should work I believe Only things that really need to be there are the README, timecheck.js, and help.js Everything else can go
> > 
> > 
> > coolio, so what's the problem?
> 
> random/Screenshot_69420.png lmao It doesn't need to be there

ahhhh

**Pull request merged**
